apiVersion: v1
kind: Service
metadata: 
 name: nginx-lb 
spec: 
 type: LoadBalancer 
 selector: 
   project: roboshop
   environment: dev 
   component: frontend
   purpose: load-balancer 
 ports: 
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007   # node port range: 30000 to 32767
   

